### ISSUE TITLE
How to install ngrok in ubuntu, debian and centos

### ISSUE THREAD

**Issue by 00itsm00** [JaniniRami07/FlaskLocator#2]
Hi Dear,

Firstly thank you for soaring some time to make this project, secondly It is requested to share how to install ngrok in subject OS, i tried to install ngrok in all of above but encountered problems. Can't share log or errors right now ll share when i am home.

Please share how to. If you can or have some time to spare.

Thanks & regards,

itsM

**Comment by JaniniRami07** [comment]
Hey, By installing the requirements file with  ``` python3 -m pip install requirements.txt ```, you will also download a package called pyngrok, this package automatically downloads ngrok in ``` /usr/local/lib/python3.7/dist-packages/pyngrok/bin/ngrok ```, and it will automatically put it in path so we can use it in python and also in the Linux command line.
